# @/graph/typeDefs/todo.gql
type Todo @key(fields: "id") {
  id: Int!
  text: String!
  done: Boolean!
  post_id: Int!
  post: Post
}

type Mutation {
  createTodo(text: String!): Todo!
}

type Query {
  getTodos: [Todo!]!
}

extend type Post @key(fields: "id") {
    id: Int! @external
    text: String! @external
    todo: [Todo] @requires (fields: "id")
  }

