# @/graph/typeDefs/post.gql
type Post @key(fields: "id") {
  id: Int!
  text: String!
  done: Boolean!
  todo: Todo!
}

type Query {
  getPosts: [Post!]!
}

extend type Todo @key(fields: "id") {
    id: Int! @external
    posts: [Post]
  }
