# @/graph/typeDefs/post.gql
type Post @key(fields: "id") {
  id: ID!
  text: String!
  done: Boolean!
  todo: Todo
}

type Mutation {
  createPost(text: String!): Post!
}

type Query {
  getPosts: [Post!]!
}

extend type Todo @key(fields: "id") {
    id: Int! @external
    text: String! @external
    post: [Post] @requires (fields: "id")
  }
