// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package customTypes

type Post struct {
	ID   string `json:"id"`
	Text string `json:"text"`
	Done bool   `json:"done"`
	Todo *Todo  `json:"todo"`
}

func (Post) IsEntity() {}

type Todo struct {
	ID   int     `json:"id"`
	Text string  `json:"text"`
	Post []*Post `json:"post"`
}

func (Todo) IsEntity() {}
