// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package customTypes

type NewPost struct {
	Text string `json:"text"`
	Done bool   `json:"done"`
}

type Post struct {
	ID   int    `json:"id"`
	Text string `json:"text"`
	Done bool   `json:"done"`
}

func (Post) IsEntity() {}
