// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package customTypes

type Post struct {
	ID   int    `json:"id"`
	Text string `json:"text"`
	Done bool   `json:"done"`
	Todo *Todo  `json:"todo"`
}

func (Post) IsEntity() {}

type Todo struct {
	ID    int     `json:"id"`
	Posts []*Post `json:"posts"`
}

func (Todo) IsEntity() {}
