// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package customTypes

type Post struct {
	ID   int     `json:"id"`
	Text string  `json:"text"`
	Todo []*Todo `json:"todo"`
}

func (Post) IsEntity() {}

type Todo struct {
	ID     string `json:"id"`
	Text   string `json:"text"`
	Done   bool   `json:"done"`
	PostID int    `json:"post_id"`
	Post   *Post  `json:"post"`
}

func (Todo) IsEntity() {}
