// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package customTypes

type NewTodo struct {
	Text   *string `json:"text"`
	Done   *bool   `json:"done"`
	PostID int     `json:"post_id"`
}

type Post struct {
	ID    int     `json:"id"`
	Posts []*Post `json:"posts"`
}

func (Post) IsEntity() {}

type Todo struct {
	ID     int     `json:"id"`
	Text   *string `json:"text"`
	Done   *bool   `json:"done"`
	PostID int     `json:"post_id"`
}

func (Todo) IsEntity() {}
